export default {
  appName: {
    full: '平安校园智慧通行管理系统',
    // full: 'LAdmin',
    subTitle: '电子科技大学',
    // subTitle: 'Material Design',
    attr: '平安成电智慧通行',
    // full path
    logoPath: '',
  },
  version: '2.0.1',
  permissionSeq: ':',
  navDrawerWidth: 300,
  denseNavDrawer: false,
  icons: {
    'person': 'mdi-account',
    'role': 'mdi-account-box',
    'group': 'mdi-account-multiple',
    'email': 'mdi-email',
    'idCard': 'mdi-credit-card',
    'idCardType': 'mdi-credit-card-settings',
    'phone': 'mdi-phone',
    'org': 'mdi-bank',
    'loginId': 'mdi-account-card-details',
    'message': 'mdi-message-text',
    'description': 'mdi-file-document',
    'car': 'mdi-car',
    'add': 'mdi-plus',
    'delete': 'mdi-delete',
    'more': 'mdi-dots-vertical',
    'deleteAll': 'mdi-delete-sweep',
    'lock': 'mdi-lock',
    'back': 'mdi-arrow-left',
    'code': 'mdi-code-tags',
    'alert': 'mdi-alert-circle',
    'comment': 'mdi-message-text',
    'location': 'mdi-map-marker',
    'edit': 'mdi-pencil',
    'folder': 'mdi-folder',
    'chevronRight': 'mdi-chevron-right',
    'details': 'mdi-dots-horizontal'
  },
}
